name: Lint & type check

on: push
jobs:
  run-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        run: yarn lint
  type-check:
    name: types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Run TSC
        run: npx tsc --noEmit
