name: Lint

on: push
jobs:
  run-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Run ESLint
        run: npm run lint
