name: Test

on: push
jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - uses: cypress-io/github-action@v6
        name: Cypress E2E run
        with:
          build: npm run build
          start: npm start
          browser: chrome
      - uses: cypress-io/github-action@v6
        name: Cypress component run
        with:
          component: true
          build: npm run build
          start: npm start
          browser: chrome
  jest-run:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: npm run test