name: Test

on: push
jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/checkout@v4
        run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome

