name: Test

on: push
jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Install dependencies
        run: yarn
      - uses: cypress-io/github-action@v6
        name: Cypress run
        with:
          build: npm run build
          start: npm start
          browser: chrome

